/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimalFacts: typeof import('./src/components/Practice/AnimalFacts.vue')['default']
    Button: typeof import('primevue/button')['default']
    CatFacts: typeof import('./src/components/Practice/CatFacts.vue')['default']
    CreatePage: typeof import('./src/components/Practice/CreatePage.vue')['default']
    HelloWorld: typeof import('./src/components/Vue/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Navbar: typeof import('./src/components/Practice/Navbar.vue')['default']
    NavbarComponent: typeof import('./src/components/Practice/NavbarComponent.vue')['default']
    NavbarContainer: typeof import('./src/components/Practice/NavbarContainer.vue')['default']
    NavbarLink: typeof import('./src/components/Practice/NavbarLink.vue')['default']
    PageContainer: typeof import('./src/components/Practice/PageContainer.vue')['default']
    PageEdit: typeof import('./src/components/Practice/PageEdit.vue')['default']
    PageList: typeof import('./src/components/Practice/PageList.vue')['default']
    PageManagement: typeof import('./src/components/Practice/PageManagement.vue')['default']
    PagesList: typeof import('./src/components/Practice/PagesList.vue')['default']
    PagesManagement: typeof import('./src/components/Practice/PagesManagement.vue')['default']
    PageViewer: typeof import('./src/components/Practice/PageViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/Vue/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/Vue/WelcomeItem.vue')['default']
  }
}
