/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimalFacts: typeof import('./src/components/Practice/AnimalFacts.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    Button: typeof import('primevue/button')['default']
    CatFacts: typeof import('./src/components/Practice/CatFacts.vue')['default']
    Column: typeof import('primevue/column')['default']
    ConditionGenerator: typeof import('./src/components/securities/ConditionGenerator.vue')['default']
    ConditionSelect: typeof import('./src/components/securities/ConditionSelect.vue')['default']
    CreatePage: typeof import('./src/components/Practice/CreatePage.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Hamburger: typeof import('./src/components/Hamburger/index.vue')['default']
    HelloWorld: typeof import('./src/components/Vue/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    NavbarContainer: typeof import('./src/components/Practice/NavbarContainer.vue')['default']
    NavbarLink: typeof import('./src/components/Practice/NavbarLink.vue')['default']
    PageEdit: typeof import('./src/components/Practice/PageEdit.vue')['default']
    PagesList: typeof import('./src/components/Practice/PagesList.vue')['default']
    PagesManagement: typeof import('./src/components/Practice/PagesManagement.vue')['default']
    PageViewer: typeof import('./src/components/Practice/PageViewer.vue')['default']
    PriceCondition: typeof import('./src/components/securities/PriceCondition.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    TheWelcome: typeof import('./src/components/Vue/TheWelcome.vue')['default']
    VolumeCondition: typeof import('./src/components/securities/VolumeCondition.vue')['default']
    WelcomeItem: typeof import('./src/components/Vue/WelcomeItem.vue')['default']
  }
}
